# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ca10546ffa57c99281f78a8583bf099ea78c1a024ba68dbafdab83dc22528ef0b4588a77fd5492d73f7696a5b08b5be8a8462983ff8ed4799a327dc47c4a1be

test:
  secret_key_base: 15e653da375c38719009ced778c19a9b4db84b228c94215d59cb05678a97a240ad9fefbd707ee03a5c0cc60cf32e5e81b79114e06950c1bdf46ddde6be8e5b87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
